server:
  port: 9003
spring:
  application:
    name: wishlist_service
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: airbnb