#spring.application.name=gateway
server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-origins: "*"
            allowed-headers: "*"
      routes:
        - id: reservation
          uri: lb://RESERVATION
          predicates:
            - Path=/api/reserve/**
        - id: room
          uri: lb://ROOM
          predicates:
            - Path=/api/v1/rooms/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**

eureka:
  client:
    service-url:
      defaultZone: http://192.168.80.39:8765/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway
