spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/user/**

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
  instance:
    prefer-ip-address: true
    instance-id: JHSeok