server:
  port: 9002
spring:
  application:
    name: reservation_service
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: airbnb